spring.application.name=uz.chemical
server.port = 9899

spring.datasource.url = jdbc:postgresql://localhost:5432/bilkom
spring.datasource.username = postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

# JWT
app.jwt.secret=ZXJwLXNlY3JldC1rZXktbWluaW11bS0zMi1jaGFyYWN0ZXJzLWxvbmctYmFzZTY0
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000